### ISSUE TITLE
GCP badge?

### ISSUE THREAD

**Issue by lynnlangit** [MikeCodesDotNET/ColoredBadges#1]
Thanks for doing this!  would it possible for you to create a GCP badge?

**Comment by MikeCodesDotNET** [comment]
Yep, I'll get that created over the weekend or on Monday.

**Comment by lynnlangit** [comment]
BTW - take a look - https://github.com/lynnlangit (using your badges on my profile)

**Comment by MikeCodesDotNET** [comment]
## Icon design checklist: 

### ICON NAME GOEs HERE

- [ ] Create icon in Figma 

- [ ] Export SVG & PNG 

- [ ] Publish to GitHub  

- [ ] Update Readme 

#### Proposed Design
<img width="87" alt="gcp@2x" src="https://user-images.githubusercontent.com/552074/87299873-be366b80-c504-11ea-8db5-c373dabb2b12.png">
<img width="223" alt="google_cloud_platform@2x" src="https://user-images.githubusercontent.com/552074/87299877-c098c580-c504-11ea-94d4-74fdf8a5e830.png">

**Comment by MikeCodesDotNET** [comment]
@lynnlangit, I've created a first draft of what the icon might look like. I wasn't sure (not being a use of GCP) if it's the norm to use the initialism or the full name, so I opted to include both. 

Does this look ok to you?

**Comment by lynnlangit** [comment]
Thanks for doing this.  I like the first one better (abbreviated).
