### ISSUE TITLE
[Icon request] Godot Engine

### ISSUE THREAD

**Issue by Beelzenef** [MikeCodesDotNET/ColoredBadges#15]
It would be awesome to have a Godot Engine badge

Godot Engine is a growing, open source game engine to make 2D and 3D videogames

* [Godot Engine repo](https://github.com/godotengine/godot)
* [Website](https://godotengine.org/)

This is the lovely logo:

![Juansky or Robi, the robot](https://godotengine.org/themes/godotengine/assets/logo.svg)

Hope it gets some likes!

**Comment by MikeCodesDotNET** [comment]
I wasn't sure if it should be "GODOT" or "Godot" so I went with the latter. If you think it should be the former then just reopen the issue with a note.


<img width="101" alt="godot@2x" src="https://user-images.githubusercontent.com/552074/87401185-b7b1fd80-c5b1-11ea-9a53-fe1005ee79ea.png">
