### ISSUE TITLE
Add Mobile Dev Icons

### ISSUE THREAD

**Issue by aking618** [MikeCodesDotNET/ColoredBadges#23]
Do you think you could add Icons for Android Studio, Flutter, and Dart

**Comment by klaasnicolaas** [comment]
I can make the Android Studio version 😉

**Comment by klaasnicolaas** [comment]
Btw this PR is a duplicate of #20 😉

**Comment by aking618** [comment]
Sorry about that 👌

**Comment by klaasnicolaas** [comment]
#31 Will add the two badges 😉
