### ISSUE TITLE
Add Docker and Laravel badge

### ISSUE THREAD

**Issue by klaasnicolaas** [MikeCodesDotNET/ColoredBadges#24]
Based on your Figma file, I made 2 new badges. One for Docker (not the hub) and Laravel framework. 

I'll be making a pull request today so they can be added, however I didn't quite figure out which category docker should fall into?

**Comment by klaasnicolaas** [comment]
I can also add badges for CSS and SASS 😉

**Comment by louisefindlay23** [comment]
@klaasnicolaas, that's great. I created an issue (#26) for CSS.
