### ISSUE TITLE
Add DigitalOcean Badge

### ISSUE THREAD

**Issue by louisefindlay23** [MikeCodesDotNET/ColoredBadges#28]
Reference Icon(s): https://fontawesome.com/icons/digital-ocean?style=brands
Preferred Background: Blue
Label Text: DigitalOcean

**Comment by klaasnicolaas** [comment]
![image](https://user-images.githubusercontent.com/20448157/87734678-9fb9c400-c7d3-11ea-9abc-78a919159ca8.png)

Badge created, will be available soon 😉

**Comment by MikeCodesDotNET** [comment]
Great work @klaasnicolaas!

**Comment by klaasnicolaas** [comment]
Just made a new PR that will add the badge 😉
