### ISSUE TITLE
Badge for R

### ISSUE THREAD

**Issue by rtelmore** [MikeCodesDotNET/ColoredBadges#4]
I'd like to have a new badge.

---Request Info:

Can you create a badge for R Software? Thank you!

**Comment by MikeCodesDotNET** [comment]
Yep, I’ll add that to the list!

**Comment by rtelmore** [comment]
Thanks a lot...this is a great project!

**Comment by MikeCodesDotNET** [comment]
## Icon design checklist: 

### R Software

- [ ] Create icon in Figma 

- [ ] Export SVG & PNG 

- [ ] Publish to GitHub  

- [ ] Update Readme 

#### Example: 
![Rlogo_scaled](https://user-images.githubusercontent.com/552074/87293229-e8cef700-c4f9-11ea-917f-e88faf15dacb.png)

---

**Comment by MikeCodesDotNET** [comment]
@rtelmore I was unsure what to name the text so I've added two options. Let me know which you think is better and I'll keep that. 

<img width="87" alt="r@2x" src="https://user-images.githubusercontent.com/552074/87294328-80811500-c4fb-11ea-981c-d1bf84ab9b85.png">

or 

<img width="135" alt="rsoftware@2x" src="https://user-images.githubusercontent.com/552074/87294335-837c0580-c4fb-11ea-8360-1a6f25ce0d6f.png">

**Comment by rtelmore** [comment]
They look great. Thanks!
