### ISSUE TITLE
Add badge for Marten

### ISSUE THREAD

**Issue by tonykaralis** [MikeCodesDotNET/ColoredBadges#44]
Marten is an awesome .NET Transactional Document DB and Event Store on PostgreSQL with over a million downloads on nuget. Would be great to get a badge created for it.

Logo url: https://github.com/JasperFx/marten/blob/master/documentation/content/images/emblem.png
Background color: White
Label Text: Marten

![image](https://user-images.githubusercontent.com/18276387/88453250-35e98c00-ce5d-11ea-8592-cf85aef50472.png)

**Comment by tonykaralis** [comment]
@jeremydmiller @mysticmind @oskardudycz @codinggorilla @jokokko thought it would be cool to get a badge done for Marten, If you'd like to see this one created then please give the issue a thumbsup and @MikeCodesDotNET will hopefully consider this 😄 

I will attempt this week to see if I can try and create the badge myself. I took the Marten logo from the repo, but is there a png version available by any chance?

**Comment by mysticmind** [comment]
@tonykaralis I think you were requesting for a SVG version, have managed to export the logo paths from the PNG file using GIMP and created an SVG file using Inkscape. Also created the badges using the Figma template file. The attached zip file contains the badges.

Below is the sample badge:
<img width="104" alt="marten@2x" src="https://user-images.githubusercontent.com/2864208/88462730-1e48ec80-cecb-11ea-935b-280bb6670202.png">

[Marten_badges.zip](https://github.com/MikeCodesDotNET/ColoredBadges/files/4976088/Marten_badges.zip)

I will add the badges and the logo SVG file in Marten repo. Please close this issue opened here.

@MikeCodesDotNET Thanks for the wonderful project, the badges look great. 👍
