### ISSUE TITLE
Badge for webstorm

### ISSUE THREAD

**Issue by zeus1200** [MikeCodesDotNET/ColoredBadges#6]
Would it be possible to add a badge for webstorm software? Thank you very much ^^

**Comment by MikeCodesDotNET** [comment]
I’ll get that added in the coming days.

**Comment by MikeCodesDotNET** [comment]
## Icon design checklist: 

### ICON NAME GOEs HERE

- [x] Create icon in Figma 

- [x] Export SVG & PNG 

- [ ] Publish to GitHub  

- [ ] Update Readme 

#### Proposed Design
<img width="133" alt="jetbrains_webstorm@2x" src="https://user-images.githubusercontent.com/552074/87306240-a6181980-c50f-11ea-9557-227fee6c9724.png">
