### ISSUE TITLE
[Icon Request] C# / F#

### ISSUE THREAD

**Issue by AlexHedley** [MikeCodesDotNET/ColoredBadges#7]
These are fab, thanks so much for doing them.

Are you planning on doing any other languages like

- C#

![C#](https://upload.wikimedia.org/wikipedia/commons/7/7a/C_Sharp_logo.svg)

[Logo Idea](https://github.com/dotnet/csharplang/issues/2708)

- F#

![F#](https://fsharp.org/img/logo/fsharp256.png)

**Comment by MikeCodesDotNET** [comment]
I'll get these added on Monday! Thanks for supplying them!

**Comment by MikeCodesDotNET** [comment]
@AlexHedley Draft icons below. If you're happy with them, then i'll submit a PR to add them to the repro

## Icon design checklist: 

### ICON NAME GOEs HERE

- [x] Create icon in Figma 

- [x] Export SVG & PNG 

- [ ] Publish to GitHub  

- [ ] Update Readme 

### Draft 

<img width="74" alt="csharp@2x" src="https://user-images.githubusercontent.com/552074/87304965-9bf51b80-c50d-11ea-911a-7ccf4834563a.png">
<img width="126" alt="csharp_dotnet@2x" src="https://user-images.githubusercontent.com/552074/87304973-9dbedf00-c50d-11ea-804b-13f4f7254d49.png">


<img width="74" alt="fsharp@2x" src="https://user-images.githubusercontent.com/552074/87304977-a1eafc80-c50d-11ea-8363-7cbc2fffc662.png">
<img width="125" alt="fsharp_dotnet@2x" src="https://user-images.githubusercontent.com/552074/87304981-a3b4c000-c50d-11ea-9aed-2a9044c6e400.png">

---

**Comment by AlexHedley** [comment]
These look fab, thanks for sorting them so quickly!
