### ISSUE TITLE
[Icon Request] - RSS & Podcast

### ISSUE THREAD

**Issue by GaProgMan** [MikeCodesDotNET/ColoredBadges#8]
Might be a bit of a left-field request, but I'd love a mic-based or RSS-like badge as I create a bunch of podcasts that are tech-related. I feel like it would fit with the other icons in the social section.

**Comment by MikeCodesDotNET** [comment]
## Icon design checklist: 

### RSS 

- [ ] Create icon in Figma 

- [ ] Export SVG & PNG 

- [ ] Publish to GitHub  

- [ ] Update Readme 

#### Example: 
![download](https://user-images.githubusercontent.com/552074/87291707-a0163e80-c4f7-11ea-8150-2e54d8fd1527.png)

--- 

### Podcast

- [ ] Create icon in Figma 

- [ ] Export SVG & PNG 

- [ ] Publish to GitHub  

- [ ] Update Readme 

#### Example: 
![mic](https://user-images.githubusercontent.com/552074/87292033-1c108680-c4f8-11ea-97b4-179b7a249d67.png)
